WIP: Password resetting
unitystation/unitystation_auth pull request #74
Opened 2024-01-13 19:27 UTC by MaxIsJoe

2024-01-13 20:09 UTC, corp-0 requested changes

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        instance.set_password(validated_data.get("password", instance.password))
I don't think ``instance.password`` works. There should be no way to get the actual password after it is set.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        newModel = PasswordResetRequestModel(token=account.verification_token, account=account)
use ``snake_case`` in python

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/urls.py
> +    path("change-password/<str:unique_identifier>/<str:token>", ChangePasswordView.as_view(), name="change-passwordd"),
the dynamic URL should not include the account identifier.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/views.py
> +            return Response(data={"error V": str(e)}, status=e.status_code)
do not return any response here. Just log that the email doesn't exist.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/views.py
> +        serializer.create(serializer.validated_data)
```suggestion
        serializer.save()
```

this will call the create method properly and actually save the new object in the database.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/views.py
> +        return Response(data={"sucess" : str(serializer)}, status=status.HTTP_200_OK)
do not return the serializer as a response. Just use a generic message that says a token has been sent if the email exists.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/models.py
> +    account = models.ForeignKey(Account, on_delete=models.CASCADE)
your model is missing a lifespan field. Tokens should die in a short time span.

2024-01-13 20:09 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        fields = ["email"]
where is the token?

2024-01-13 20:12 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        fields = ("password")
this evaluates to `fields = "password"`. you want `("password",)` if this should be tuple

2024-01-13 20:29 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        fields = ("password")
it should indeed be a tuple. Thanks for catching it

2024-01-13 20:33 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        fields = ["email"]
ah nevermind, you don't pass a token here. My bad.

2024-01-17 17:21 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        token = account.verification_token  # Replace with the actual field name
This is the wrong token.

2024-01-17 20:06 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        fields = ("password")
i cant mark this resolved for some reason

2024-01-17 20:08 UTC, MaxIsJoe commented on src/accounts/api/serializers.py
> +        token = account.verification_token  # Replace with the actual field name
token uses uuid for now, should convert to `secrets.token_urlsafe(32)` but it keeps breaking the thingy majingy and silently fails

2024-01-18 21:53 UTC, corp-0 requested changes
It is looking good overall. Just some details

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        new_model_data = {"token": token, "account": account, "created_at": timezone.now() + timezone.timedelta(minutes=35)}
```suggestion
        new_model_data = {"token": token, "account": account)}
```
You don't need to pass anything here. The models needs to register the creation date time itself.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        print(validated_data)
just remember to remove the prints later.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/urls.py
> +    path("change-password/", RequestPasswordResetView.as_view(), name="change-password"),
call this url what it really is, ``reset-password``

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +class ChangePasswordView(GenericAPIView):
```suggestion
class ResetPasswordView(GenericAPIView):
```

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/serializers.py
> +class ChangePasswordRequestSerializer(serializers.ModelSerializer):
```suggestion
class ResetPasswordRequestSerializer(serializers.ModelSerializer):
```

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/serializers.py
> +class ChangePasswordSerializer(serializers.ModelSerializer):
```suggestion
class ResetPasswordSerializer(serializers.ModelSerializer):
```

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +from django.contrib.auth.models import User
```suggestion
from .accounts.models import Account
```

use our Account class instead of the base User class.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +            if(reset_request.is_token_valid() == False):
```suggestion
            if not reset_request.is_token_valid():
```

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +            if serializer.is_valid():
you already checked this on line 200

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +            reset_request = PasswordResetRequestModel.objects.get(token=reset_token)
this could throw a PasswordResetRequestModel.DoesNotExistException.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +                return Response(data={"Operation Done": "Changed password succesfully"}, status=status.HTTP_200_OK)
see what I'm returning on other endpoints. It is important to have a consistent structure on our returns. I should probably make it a class even, so we all have the same everywhere.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/api/views.py
> +            # Though maybe we can add a -dev flag check to report errors while not in a production environment?
add a log. I should have logs somewhere else in the project so you can see how to use it.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/models.py
> +    def is_token_valid(self):
add an empty line in between the fields and the method.

2024-01-18 21:53 UTC, corp-0 commented on src/accounts/models.py
> +        return timezone.now() <= self.created_at + 30
this implementation doesn't look right. It should be something like
```suggestion
        return timezone.now() <= timedelta(minutes=30)
```

Although I suggested on Discord to make this an hour instead.

We should probably include a command as well, so we can periodically look for dead tokens and remove them from the database.

2024-01-18 22:19 UTC, Fogapod commented on src/accounts/api/urls.py
> +    path("reset-password/<str:reset_token>", ChangePasswordView.as_view(), name="change-passwordd"),
`passwordd`

2024-01-18 23:04 UTC, corp-0 commented on src/accounts/api/urls.py
> +    path("reset-password/<str:reset_token>", ChangePasswordView.as_view(), name="change-password"),
This name field is used to uniquely identify this URL. While we don't really use it, since we are not presenting links to the user and only use this as a backend, I still think the name should be equal to the friendly URL.

2024-01-18 23:05 UTC, MaxIsJoe commented on src/accounts/api/urls.py
> +    path("reset-password/<str:reset_token>", ChangePasswordView.as_view(), name="change-password"),
done

2024-01-18 23:06 UTC, corp-0 commented on src/accounts/api/urls.py
> +    path("reset-password/", RequestPasswordResetView.as_view(), name="reset-password"),
These two can't have the same name

2024-01-19 00:09 UTC, Fogapod reviewed
a few style comments

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        fields = ["email"]
please either use [] or () for fields

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        email = data.get("email")
why is it .get? it can return None unlike []

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        # Note: Make this silently fail later; users don't need to know about this.
is it NOTE or TODO? 

what is this about?

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        return reset_request
return it directly instead of creating variable

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/views.py
> +        print(str(reset_token))
remove print

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/views.py
> +        except (TypeError, ValueError, OverflowError, PasswordResetRequestModel.DoesNotExist):
this is a huge try except block. it's not clear where errors are coming from

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/api/views.py
> +            print(str(e))
remove print

2024-01-19 00:09 UTC, Fogapod commented on src/accounts/models.py
> +        return f"{self.token} as {str(self.account)} created at {str(self.created_at)}"
do not do str() in f-strings, it's already happening

2024-01-19 00:35 UTC, MaxIsJoe commented
done

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        return new_model_data
separate `token` and `new_model_data` are not needed here
```python
        return {
            "token": secrets.token_urlsafe(32),
            "account": account,
            "created_at": timezone.now() + timezone.timedelta(minutes=35),
        }
```

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/views.py
> +            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
you shouldnt show internal errors to user

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/views.py
> +        return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
what are these `detail` fields? (applies to all other instances)
i don't see this used in other endpoints and this looks redundant. just return HTTP 200

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/views.py
> +                    return Response({"error": "Invalid link or expired."}, status=status.HTTP_400_BAD_REQUEST)
`is_token_valid` only fails when db record is expired, so should probably say `Expired token`

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/views.py
> +        return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
```python
def post(self, request):
    serializer = self.serializer_class(data=request.data)

    # we dont care if validation fails
    with contextlib.suppress(ValidationErrorSomething - what is_valid raises):
        serializer.is_valid(raise_exception=True)
        serializer.save()

    return Response(status=status.HTTP_200_OK)
```

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/migrations/0006_auto_20240118_2053.py
> +    ]
all these 5 migrations need to be merged into 1

2024-01-19 15:06 UTC, Fogapod commented on src/accounts/api/serializers.py
> +        fields = ["email"]
this is still inconsistent
```py
      fields = ("password",)
      fields = ["email"]
```

2024-01-21 00:22 UTC, corp-0 requested changes

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/serializers.py
> +            "created_at": timezone.now() + timezone.timedelta(minutes=35),
I think I told you before you don't need to modify this field. Django will auto get the time of creation when you create the object. Also adding 35 minutes to the time of creation makes no sense.

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/views.py
> +                    return Response({"error": "Invalid link or expired."}, status=status.HTTP_400_BAD_REQUEST)
I don't have an issue with it saying invalid or expired. Now, I think it should instead raise an exception so it is handled with the rest of errors.

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/views.py
> +            else:
this else makes no sense

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/views.py
> +        return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
that's why I think standardising (either by creating a class or agreeing on how to return responses) is needed.

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/views.py
> +            return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
log the attempt. No need to return here, since you are returning outside the try block anyways.

2024-01-21 00:22 UTC, corp-0 commented on src/accounts/api/views.py
> +        serializer.save()
it is missing sending the email here, so the users get a link to the website and they can reset their password there. 

This mean you would have to add a value to settings.py as well, a way to get the website URL so you can append the token.

```python
# settings.py

WEBSITE_URL = os.environ.get("WEBSITE_URL", "https://unitystation.org/reset-password/%s")
```

See here to know how to send the email https://docs.djangoproject.com/en/3.2/topics/email/

you could use the account confirmation email template as a base for this one, you can find it here https://github.com/unitystation/central-command/blob/f65f4bd0ec1c9a3362c514a45b1c85ced4058b65/src/templates/confirm_template.html

2024-01-21 19:25 UTC, MaxIsJoe commented on src/accounts/api/views.py
> +        serializer.save()
send email added
i don't know how to use email templates since nothing seems to be using this example, so im leaving it at that

2024-01-21 19:27 UTC, MaxIsJoe commented on src/accounts/api/views.py
> +            return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
can't return after sending an email

2024-01-21 19:35 UTC, corp-0 commented on src/accounts/api/views.py
> +            return Response(data={"detail": "Operation Done."}, status=status.HTTP_200_OK)
Right. In any case, you should be handling the specific exception of ValidationError here. You need to handle known exceptions, not a one case catches all.

2024-01-21 19:38 UTC, corp-0 commented on src/central_command/settings.py
> +EMAIL_PASSWORD_RESET = os.environ.get("WEBSITE_URL", "https://unitystation.org/reset-password/")
This variable is not storing an email, why name it that.

2024-01-21 19:41 UTC, corp-0 commented on src/accounts/api/serializers.py
> +        account = Account.objects.filter(email=email).first()
On second thought, this should use get instead of filter. The email field is unique in the database

2024-01-21 23:05 UTC, corp-0 requested changes

2024-01-21 23:05 UTC, corp-0 commented on src/accounts/api/serializers.py
> +            "created_at": timezone.now(),
```suggestion
```

this is not needed. The field will be auto filled with the time of creation when you create the object.

2024-01-21 23:05 UTC, corp-0 commented on src/accounts/api/views.py
> +        serializer.save()
```python
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

def send_email(recipient: str, context: dict) -> None:
    email_subject = 'Unitystation: Password Reset Request'
    email_body = render_to_string('email_password_reset.html', context)

    email = EmailMessage(
        email_subject, 
        email_body, 
        settings.EMAIL_HOST_USER, 
        [recipient_email]
    )
    email.content_subtype = 'html'
    email.send()
```

``context`` is just a dictionary with your data, like 

```python
context = {"token": token}
```

2024-01-23 23:40 UTC, corp-0 approved these changes

2024-01-23 23:40 UTC, merged