feat: adds homemade mail confirmation and removes external library
unitystation/unitystation_auth pull request #77
Opened 2024-01-24 20:49 UTC by corp-0

Removes the previous plugin we were using to send mail confirmation because it blocked us from updating the django version.

Instead I wrote our own mail confirmation.

This PR also adds a plugin that will help us handle non-blocking mails.

2024-01-24 20:59 UTC, corp-0 commented
someone review me :B

2024-01-24 21:15 UTC, MaxIsJoe approved these changes
LGTM

2024-01-26 17:32 UTC, Fogapod commented on Dockerfile
> +COPY poetry.lock pyproject.toml ./
why this change?

2024-01-26 17:32 UTC, Fogapod commented on api-collection/Auth/Mail confirmation/Resend mail confirmation.bru
> +    "email": "mail@mail.com"
i dont know what this file is, but shouldnt this be something@unitistation.org ?

2024-01-26 17:32 UTC, Fogapod commented on src/accounts/api/views.py
> +        except Account.DoesNotExist:
```python
            account.is_active = True
            account.is_confirmed = True
            account.save()
```
this should be outside try block (unless it raises DoesNotExist) too somehow

2024-01-26 17:32 UTC, Fogapod commented on src/accounts/api/views.py
> +        except Exception as e:
what else can go wrong? save can fail? im not sure this is required block

2024-01-26 17:32 UTC, Fogapod commented on src/accounts/api/views.py
> +        except Exception as e:
what else can go wrong here? is this required?

2024-01-26 17:32 UTC, Fogapod commented on src/central_command/settings.py
> +WEBSITE_URL = os.environ.get("WEBSITE_URL", "https://unitystation.org")
why does it have a default instead of having it in default .env file

2024-01-26 17:32 UTC, Fogapod commented on src/central_command/settings.py
> +ACCOUNT_CONFIRMATION_TOKEN_TTL = 24  # hours
why such a huge (24x) difference between password reset and account confirmation? shouldnt they be the same?

2024-01-26 17:45 UTC, corp-0 commented on Dockerfile
> +COPY poetry.lock pyproject.toml ./
dunno, IDE was mad about it not having / and told me to do it

2024-01-26 17:47 UTC, corp-0 commented on api-collection/Auth/Mail confirmation/Resend mail confirmation.bru
> +    "email": "mail@mail.com"
this file is just what you see when you open bruno (postman alternative). You would change it to something else when you are trying the endpoint locally. I don't know how to parametrise that in bruno to make it more obvious that you have to/can change it.

2024-01-26 17:47 UTC, corp-0 commented on src/accounts/api/views.py
> +        except Exception as e:
I don't know. Anything, probably.

2024-01-26 17:48 UTC, corp-0 commented on src/central_command/settings.py
> +WEBSITE_URL = os.environ.get("WEBSITE_URL", "https://unitystation.org")
I forgot to add it to default.env. Why are you against having a default value in code tho?

2024-01-26 17:49 UTC, corp-0 commented on src/central_command/settings.py
> +ACCOUNT_CONFIRMATION_TOKEN_TTL = 24  # hours
I looked up what people normally set for TTL for a confirmation mail token and they all said 12-24 hours.

What is the argument for having both confirmation and password reset have same lifespan?

2024-01-26 18:29 UTC, Fogapod commented on src/accounts/api/views.py
> +        except Exception as e:
generic 500 error should be handled globally. this shouldnt be a copypaste with only difference being error message variation like "account creation failed" or similar

2024-01-26 18:30 UTC, Fogapod commented on src/central_command/settings.py
> +WEBSITE_URL = os.environ.get("WEBSITE_URL", "https://unitystation.org")
because this is how its documented now. and its better to either go full code or full settings file

2024-01-26 18:31 UTC, Fogapod commented on src/central_command/settings.py
> +ACCOUNT_CONFIRMATION_TOKEN_TTL = 24  # hours
because it is using exact same system and user actions are the same. i am not saying it should be 1 variable but times differing so much is weird

2024-01-26 23:12 UTC, Fogapod commented on api-collection/Auth/Mail confirmation/Resend mail confirmation.bru
> +    "email": "mail@mail.com"
could you mention this thing in readme?

2024-01-26 23:28 UTC, Fogapod requested changes

2024-01-26 23:28 UTC, Fogapod commented on Dockerfile
> +    && mkdir /home/website/logs \
final `\` - this is kinda ugly and might even be invalid syntax. did you check docker build?

2024-01-26 23:31 UTC, corp-0 commented on Dockerfile
> +    && mkdir /home/website/logs \
I think I did, and our ci also builds. I will remove it nonetheless

2024-02-06 21:07 UTC, corp-0 commented on src/accounts/api/views.py
> +        except Exception as e:
Alright, I should add a response for unhandled exceptions then. Will do

2024-02-07 01:46 UTC, merged